<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

<<<<<<< HEAD
if (\class_exists(\Container3X8GI5T\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3X8GI5T/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3X8GI5T.legacy');
=======
if (\class_exists(\ContainerHDKVFLq\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHDKVFLq/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHDKVFLq.legacy');
>>>>>>> a598839269f693caa1a6b5595f913cdb1e5085bd

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
<<<<<<< HEAD
    \class_alias(\Container3X8GI5T\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container3X8GI5T\App_KernelDevDebugContainer([
    'container.build_hash' => '3X8GI5T',
    'container.build_id' => '11fca8cd',
    'container.build_time' => 1676277046,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3X8GI5T');
=======
    \class_alias(\ContainerHDKVFLq\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHDKVFLq\App_KernelDevDebugContainer([
    'container.build_hash' => 'HDKVFLq',
    'container.build_id' => 'd900cc86',
    'container.build_time' => 1676277518,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHDKVFLq');
>>>>>>> a598839269f693caa1a6b5595f913cdb1e5085bd
