<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3X8GI5T\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3X8GI5T/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3X8GI5T.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container3X8GI5T\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container3X8GI5T\App_KernelDevDebugContainer([
    'container.build_hash' => '3X8GI5T',
    'container.build_id' => '11fca8cd',
    'container.build_time' => 1676277046,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3X8GI5T');
