<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJratb1I\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJratb1I/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJratb1I.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJratb1I\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJratb1I\App_KernelDevDebugContainer([
    'container.build_hash' => 'Jratb1I',
    'container.build_id' => '04d4ac8e',
    'container.build_time' => 1676897841,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJratb1I');
